name: Deploy static content to AirLineWeb

  # Indicar que se ejecute cada vez que haga un push
  on:
  push:
    branches: ["dev_luis"]

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Node
          uses: actions/setup-node@v4

        - name: install Dependencies
          run: npm install

        - name: Build app
          run: npm run build

        - name: Artifact upload
          uses: actions/upload-pages-artifact@v3
          with:
            name: github-AirLine
            path: dist/admin-library-front/browser

deploy:
  needs: build
  permissions:
    pages: write
    id-token: write
  runs-on: ubuntu-latest
  steps:
    - name: Deploy to Github
    id: deployment
    uses: actions/deploy-pages@v4